adminUser:
  password: vault:beakpear/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:beakpear/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:beakpear/prow:hmacToken
segmentWriteKey: vault:beakpear:segmentWriteKey
